# yamllint disable rule:document-start
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/czishrink"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      czishrink:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      # FluentAssertions is non-free from version 8.0.0 onwards
      - dependency-name: "FluentAssertions"
        versions: [ ">=8.0.0" ]
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
